language: node_js
node_js:
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

notifications:
  email: false

script:
  - npm validate
  - npm security
