language: node_js
node_js:
  - "8"
  - "7"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

notifications:
  email: true

script:
  - npm run validate
  - npm run validate

